### ISSUE TITLE
Trouble with figures in Jupyter Notebooks, Docker in Linux

### ISSUE THREAD

**Issue by plovely** [underworldcode/UWGeodynamics#161] opened 2020-03-02 17:22 UTC
Another issue apparently related to my transition to Docker on Linux.  Containers hang when plotting figures, with an error “Server start failed:  [Errno 97] Address family not supported by protocol 97 8080.”

I encounter the same error using UWGeodynamics:latest and using underworld2:2.9.1b.

Below is a screenshot of the error in UWGeo Tutorial_1:
![image](https://user-images.githubusercontent.com/30320218/75700546-db664e00-5c77-11ea-94b7-91badd1abf36.png)

Thanks,
Pete

**Comment by julesghub** [comment] 2020-03-17 00:16
I can't reproduce this error with the image `underworldcode/underworld2:2.9.1.b`. 

I tested it using Kitematic and with the following cmdline 
```bash
docker run --rm -it \
  -p 127.0.0.1:8888:8888 \
  -v /home/julian:/home/jovyan/workspace \
  underworldcode/underworld2:2.9.1b
```

How did you run this test? Under what environment and machine?

**Comment by plovely** [comment] 2020-03-19 17:05
I ran the test using docker run -p localhost:8888 underworldcode/underworld2:2.9.1b on a machine running RHEL 7.

**Comment by plovely** [comment] 2020-03-19 18:09
I have the same error when using your cmdline, except without the mapped volume.

**Comment by julesghub** [comment] 2020-03-19 23:45
The `show()` (lavavu's viewer) runs on a separate thread and that doesn't look able to start. Perhaps the docker configuration is restricted in someway, e.g. container doesn't allow multiple threads, can't run on port 8080.
  
@OKaluza any ideas on this problem?

**Comment by OKaluza** [comment] 2020-03-20 00:24
I can't duplicate this here, there must be a difference in my docker configuration. @jmansour reported a similar issue and worked around it with my suggestion of disabling the server thread, this allows plotting figure images but no interactive plots.  
I'll keep trying to duplicate it but until I can I have no easy fix.

**Comment by rbeucher** [comment] 2020-03-27 03:33
Any update on this all?

**Comment by OKaluza** [comment] 2020-03-27 04:14
I've put some extra checks and fall-backs into lavavu which are now in dev/master and I'll push out a new release soon, but unless you update the lavavu version they won't help.
I have not been able to reproduce the error though, so it's difficult to know if it will solve the issue for good.

**Comment by rbeucher** [comment] 2020-06-18 01:33
Keeping this for now,

**Comment by rbeucher** [comment] 2020-06-24 01:36
Closing for now, will reopen if the issue shows up again

**Closed by rbeucher** 2020-06-24 01:36 UTC
