### ISSUE TITLE
Paraview crashes while trying to open FSE files

### ISSUE THREAD

**Issue by BenedicteCT** [underworldcode/UWGeodynamics#101] opened 2019-03-22 00:18 UTC
Paraview crashes while trying to open FSE files:
Tried for UWGeodynamics Tutorial1 and Tutorial2 / three versions of paraview 5.6, 5.5, 4.4 / two Mac computers on High Sierra and Mojave respectively

The following error occurs after running none to a few time steps of FSE:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000012cda5000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [3446]

**Comment by rbeucher** [comment] 2019-03-22 03:25
HI @BenedicteCT, can you tell me what version of the code you are using? Is it in a docker?

**Comment by BenedicteCT** [comment] 2019-03-22 03:34
Hi Romain,

Yes I have been running it from a docker. Just installed it 10 days ago following the instructions on the underworldcode.org website. It looks like it is the latest version.

Thanks
Bénédicte

De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : vendredi 22 mars 2019 à 2:25 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


HI @BenedicteCT<https://protect-au.mimecast.com/s/QaYqCzvOWKiQGBE5UXmIEr?domain=github.com>, can you tell me what version of the code you are using? Is it in a docker?

**Comment by rbeucher** [comment] 2019-03-22 03:44
Are you using the "latest" tag or le "v2.7.1". 
I encourage you to use "v2.7.1"
I am going to look at the other one

**Comment by rbeucher** [comment] 2019-03-22 03:46
Can you run GEO.__version__ for me and tell me what the output is?

**Comment by BenedicteCT** [comment] 2019-03-22 03:52
I have re-downloaded the latest version of UW this morning so I think it is v.2.7.1.



De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : vendredi 22 mars 2019 à 2:44 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


Are you using the "latest" tag or le "v2.7.1".
I encourage you to use "v2.7.1"
I am going to look at the other one

**Comment by rbeucher** [comment] 2019-03-22 03:57
I have just tried with the latest docker and it's fine on my machine using Paraview 5.6.
I am going to send you some  files so that you can try to open them. Can you do the same from your side.
You can just run the code for 1 timestep, zip it and attached it here

**Comment by BenedicteCT** [comment] 2019-03-22 03:57
2.7.2



De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : vendredi 22 mars 2019 à 2:46 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


Can you run GEO.version for me and tell me what the output is?

**Comment by BenedicteCT** [comment] 2019-03-22 04:03
Ok, i will try with the file you will send me. Note that I only have issues with the FSE files, the rest is fine (even swarms).

De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : vendredi 22 mars 2019 à 2:57 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


I have just tried with the latest docker and it's fine on my machine using Paraview 5.6.
I am going to send you some files so that you can try to open them. Can you do the same from your side.
You can just run the code for 1 timestep, zip it and attached it here

**Comment by rbeucher** [comment] 2019-03-22 04:24
Will do that later today.

**Comment by rbeucher** [comment] 2019-03-22 06:39
[BenedicteCT.tar.gz](https://github.com/underworldcode/UWGeodynamics/files/2995266/BenedicteCT.tar.gz)
OK Try this.

**Comment by arijitlaik** [comment] 2019-03-22 06:42
speaking of docker images? is there a one with uw>=2.7.0 and badlands?
totally unrelated, sorry about asking
Arijit Laik,
*Faculteit der Bètawetenschappen: Geologie en geochemie D (2923D)* |*
Promovendus*
*(PhD Candidate**, Geology and Geochemistry Cluster, Department of Earth
Sciences,*
*Faculty of Science, Vrije University Amsterdam)*
[image: email_vu_logo_beta_en.png]
☎️ +31 20 59 87294, 📱 +91 8116114002
📧 a.laik@vu.nl,laikarijit@gmail.com
https://alaik.me
🏢 Gebouw Wis- en Natuurkunde E-229,
De Boelelaan 1081- 1087, 1081 HV, Amsterdam

**Comment by rbeucher** [comment] 2019-03-22 08:24
I have updated the Dockerfile, the badlands tag should give you v2.7.3

**Comment by rbeucher** [comment] 2019-03-22 08:25
@arijitlaik Can you open the files?

**Comment by rbeucher** [comment] 2019-03-22 08:25
I don't have a mac handy

**Comment by arijitlaik** [comment] 2019-03-22 13:17
Ya. The files work on Linux, I do have a Mac sans the os. And thanks :)

**Comment by BenedicteCT** [comment] 2019-03-25 02:54
I get the same random paraview 5.6 crash (one FSE file may open but running the movie crashes erratically) with the files you sent me as well. Have you tried the FSE files I sent you on Friday ?

Patrice reproduces the same paraview 5.6 erratic crash with my FSE files (generated by UWGeo.latest) whereas his files are running fine. He has noticed two differences in the single h5 files: the git commit reference number is different and in the time line “none” is written instead of the actual time step in my files.

I have downloaded the UWGeo 2.7.1 this morning and paraview (5.6 and 5.5 and 4.4) crashes erratically as well while opening/running FSE files.







De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : vendredi 22 mars 2019 à 5:39 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


BenedicteCT.tar.gz<https://protect-au.mimecast.com/s/JzS2C1WZXri2nkjLuGbPAR?domain=github.com>
OK Try this.

**Comment by rbeucher** [comment] 2019-03-25 04:23
Did you send me something?

**Comment by rbeucher** [comment] 2019-03-25 04:24
Oh yes.. went straight into the spam folder

**Comment by BenedicteCT** [comment] 2019-03-25 04:25
Oups I used the U Montpellier file sender. Is the link still active ?

De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : lundi 25 mars 2019 à 3:24 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


Oh yes.. went straight into the spam folder

**Comment by rbeucher** [comment] 2019-03-25 04:26
Well I need access and that's not going to work from Australia.
Just send it to rbeucher@unimelb.edu.au

**Comment by rbeucher** [comment] 2019-03-25 04:29
Or via the sydney system, as it looks like you are there...

**Comment by BenedicteCT** [comment] 2019-03-25 04:36
FSE zip file sent to rbeucher@unimelb.edu.au<mailto:rbeucher@unimelb.edu.au> via wetransfer.


De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : lundi 25 mars 2019 à 3:29 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


Or via the sydney system, as it looks like you are there...

**Comment by rbeucher** [comment] 2019-03-25 04:45
Hi Benedicte,

I have just tried and it runs fine.
![Peek 2019-03-25 15-43](https://user-images.githubusercontent.com/3680918/54895688-ea476b00-4f14-11e9-8c80-8fe7263ee0e6.gif)
I am going to ask someone with a mac

**Comment by rbeucher** [comment] 2019-03-25 04:47
Do you use a 32-bit or 64-bit version of Paraview?

**Comment by BenedicteCT** [comment] 2019-03-25 04:48
64-bit version of Paraview

De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : lundi 25 mars 2019 à 3:47 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


Do you use a 32-bit or 64-bit version of Paraview?

**Comment by BenedicteCT** [comment] 2019-03-25 04:51
Does the movie runs from beginning to end without erratically crashing ?

Ok let me know, we have tested on macs only (10.13 and 10.14)

De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : lundi 25 mars 2019 à 3:46 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


Hi Benedicte,

I have just tried and it runs fine.
[Image supprimée par l'expéditeur. Peek 2019-03-25 15-43]<https://protect-au.mimecast.com/s/8tDkCgZowLHOmVyXINxiqH?domain=user-images.githubusercontent.com>
I am going to ask someone with a mac

**Comment by rbeucher** [comment] 2019-03-25 05:27
OK. I managed to reproduce the issue on a Mac with Paraview 5.4.

**Comment by BenedicteCT** [comment] 2019-03-25 05:30
OK. For me the issue was the same on paraview 5.6, 5.5 and 4.4. Let me know when you have managed to fix the problem or need any further testing.

De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : lundi 25 mars 2019 à 4:27 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


OK. I managed to reproduce the issue on a Mac with Paraview 5.4.

**Comment by arijitlaik** [comment] 2019-03-25 07:06
I'll have access to a mac today, ill try out and let you people know. I do have something similar(bunch of passive tracers) with uw, but i haven't had any issue with them before.

**Comment by rbeucher** [comment] 2019-03-25 07:42
I think I know where the error comes from. The global Indices are stored as LongInt (Int8) but the xdmf specifies float 8 (double). Looks like on Linux, it's fine but on Mac it crashes.

**Comment by rbeucher** [comment] 2019-03-25 07:43
Can you try this new set of files? https://www.dropbox.com/s/jhphm5tdykgt1he/FSE.zip?dl=0

**Comment by rcarluccio** [comment] 2019-03-25 07:55
it crashed on my Paraview, the problem starts at the 24th timestep.

**Comment by arijitlaik** [comment] 2019-03-25 08:15
Yup. It crashes faster 4th timestep. Paraview 5.6 Mac 10.14.3

**Comment by rbeucher** [comment] 2019-03-25 08:17
Even the last set of files?

**Comment by rcarluccio** [comment] 2019-03-25 08:20
Yes,i think we both have tried to open them.

**Comment by arijitlaik** [comment] 2019-03-25 08:24
yes
this one
> Can you try this new set of files? https://www.dropbox.com/s/jhphm5tdykgt1he/FSE.zip?dl=0

**Comment by BenedicteCT** [comment] 2019-03-25 22:29
Paraview crashes in a similar erratic way with these files.

De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : lundi 25 mars 2019 à 6:43 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


Can you try this new set of files? https://www.dropbox.com/s/jhphm5tdykgt1he/FSE.zip?dl=0

**Comment by rbeucher** [comment] 2019-03-26 05:11
OK can one of you try those sets of files?
https://www.dropbox.com/s/282ji420qohj0mj/FSE_set1.zip?dl=0

https://www.dropbox.com/s/txasydex9zbzlys/FSE_set2.zip?dl=0

It's not easy to debug that one without a mac...

**Comment by BenedicteCT** [comment] 2019-03-26 05:40
The two dropbox links seems to point to the same set-1 zip file.

Paraview  5.6 on OSX 10.13 does not seem to crash opening and running the 20 time steps of  FSE-set-1.

De : Romain Beucher <notifications@github.com>
Répondre à : underworldcode/UWGeodynamics <reply@reply.github.com>
Date : mardi 26 mars 2019 à 4:11 PM
À : underworldcode/UWGeodynamics <UWGeodynamics@noreply.github.com>
Cc : Benedicte Cenki-Tok <benedicte.cenki-tok@sydney.edu.au>, Mention <mention@noreply.github.com>
Objet : Re: [underworldcode/UWGeodynamics] Paraview crashes while trying to open FSE files (#101)


OK can one of you try those sets of files?
https://www.dropbox.com/s/282ji420qohj0mj/FSE_set1.zip?dl=0

https://www.dropbox.com/s/txasydex9zbzlys/FSE_set2.zip?dl=0

It's not easy to debug that one without a mac...

**Comment by rbeucher** [comment] 2019-03-26 06:07
Sorry...
https://www.dropbox.com/s/kgn3yx77mksy9ka/FSE_set2.zip?dl=0

**Comment by BenedicteCT** [comment] 2019-03-26 22:27
I have tried a couple of time both sets and paraview 5.6 and 5.5 does not seem to crash. The movie for the 20 time steps runs fine.

**Comment by rbeucher** [comment] 2019-03-27 02:37
OK try to get the latest docker or the v2.7.4. (should be available in 30min)
I am closing this now, feel free to reopen if there is still an issue

**Closed by rbeucher** 2019-03-27 02:37 UTC

**Comment by BenedicteCT** [comment] 2019-03-27 04:21
Runs fine. Thanks !
